import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { Redis } from "@upstash/redis";
import { Ratelimit } from "@upstash/ratelimit";

export const runtime = "nodejs";

const resend = new Resend(process.env.RESEND_API_KEY || "");
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || "SnapSpec <noreply@snapspec.ai>";

const redis = Redis.fromEnv();

const emailLimiter = new Ratelimit({
  redis,
  limiter: Ratelimit.slidingWindow(5, "1 h"),
  analytics: true,
  prefix: "snapspec:email"
});

function getClientIp(request: NextRequest) {
  const forwardedFor = request.headers.get("x-forwarded-for");
  if (forwardedFor) return forwardedFor.split(",")[0]?.trim() || "unknown";
  return request.headers.get("x-real-ip") || "unknown";
}

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function buildEmailHtml(jira: string, notion: string, confluence: string) {
  const escape = (str: string) =>
    str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const section = (title: string, content: string) => `
    <div style="margin-bottom:32px;">
      <h2 style="font-size:16px;font-weight:600;color:#18181b;margin:0 0 12px 0;padding-bottom:8px;border-bottom:1px solid #e4e4e7;">
        ${title}
      </h2>
      <pre style="font-family:ui-monospace,monospace;font-size:13px;line-height:1.7;color:#3f3f46;white-space:pre-wrap;word-break:break-word;margin:0;background:#fafafa;border:1px solid #e4e4e7;border-radius:12px;padding:16px;">${escape(content || "No content generated.")}</pre>
    </div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width,initial-scale=1" /></head>
<body style="margin:0;padding:0;background:#ffffff;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#ffffff;">
    <tr>
      <td align="center" style="padding:40px 16px;">
        <table width="100%" style="max-width:640px;">

          <tr>
            <td style="padding-bottom:32px;">
              <div style="display:inline-flex;align-items:center;gap:8px;border:1px solid #e4e4e7;border-radius:999px;padding:6px 14px;font-size:13px;color:#52525b;font-weight:500;">
                ✦ SnapSpec
              </div>
            </td>
          </tr>

          <tr>
            <td style="padding-bottom:32px;">
              <h1 style="font-size:24px;font-weight:600;color:#09090b;margin:0 0 8px 0;letter-spacing:-0.02em;">
                Your specs are ready
              </h1>
              <p style="font-size:14px;color:#71717a;margin:0;line-height:1.6;">
                Generated by SnapSpec — Jira, Notion, and Confluence output from your screenshots.
              </p>
            </td>
          </tr>

          <tr>
            <td>
              ${section("Jira", jira)}
              ${section("Notion", notion)}
              ${section("Confluence", confluence)}
            </td>
          </tr>

          <tr>
            <td style="padding-top:32px;border-top:1px solid #e4e4e7;">
              <p style="font-size:12px;color:#a1a1aa;margin:0;text-align:center;">
                Sent from <a href="https://snapspec.ai" style="color:#52525b;text-decoration:none;">snapspec.ai</a> — from screenshots to production-ready specs.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function buildEmailText(jira: string, notion: string, confluence: string) {
  const divider = "\n" + "-".repeat(50) + "\n\n";
  return [
    "YOUR SPECS FROM SNAPSPEC",
    "snapspec.ai\n",
    "JIRA\n",
    jira || "No content generated.",
    divider,
    "NOTION\n",
    notion || "No content generated.",
    divider,
    "CONFLUENCE\n",
    confluence || "No content generated."
  ].join("\n");
}

export async function POST(req: NextRequest) {
  try {
    const ip = getClientIp(req);

    const body = await req.json() as {
      email?: unknown;
      jira?: unknown;
      notion?: unknown;
      confluence?: unknown;
    };

    const { email, jira = "", notion = "", confluence = "" } = body;

    if (!email || typeof email !== "string" || !isValidEmail(email)) {
      return NextResponse.json({ error: "A valid email address is required." }, { status: 400 });
    }

    if (typeof jira !== "string" && typeof notion !== "string" && typeof confluence !== "string") {
      return NextResponse.json({ error: "No spec content to send." }, { status: 400 });
    }

    const rateLimitResult = await emailLimiter.limit(`email:${ip}`);
    if (!rateLimitResult.success) {
      return NextResponse.json(
        { error: "Too many email requests. Please wait before sending again." },
        {
          status: 429,
          headers: {
            "Retry-After": String(Math.max(1, Math.ceil((rateLimitResult.reset - Date.now()) / 1000)))
          }
        }
      );
    }

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json({ error: "Email service is not configured." }, { status: 500 });
    }

    const { error } = await resend.emails.send({
      from: FROM_EMAIL,
      to: email,
      subject: "Your SnapSpec — Jira, Notion & Confluence specs",
      html: buildEmailHtml(String(jira), String(notion), String(confluence)),
      text: buildEmailText(String(jira), String(notion), String(confluence))
    });

    if (error) {
      return NextResponse.json({ error: "Failed to send email. Please try again." }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json({ error: "Unexpected error sending email." }, { status: 500 });
  }
}
