import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { Redis } from "@upstash/redis";
import { Ratelimit } from "@upstash/ratelimit";

export const runtime = "nodejs";

const resend = new Resend(process.env.RESEND_API_KEY || "");
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || "SnapSpec <noreply@snapspec.ai>";

type EmailScreenshotPayload = {
  content: string;
  contentType: string;
  filename: string;
};

let emailLimiter: Ratelimit | null | undefined;

function getEmailLimiter() {
  if (emailLimiter !== undefined) {
    return emailLimiter;
  }

  if (!process.env.UPSTASH_REDIS_REST_URL || !process.env.UPSTASH_REDIS_REST_TOKEN) {
    console.warn("Upstash Redis env vars are missing. Email rate limiting is disabled.");
    emailLimiter = null;
    return emailLimiter;
  }

  try {
    const redis = Redis.fromEnv();

    emailLimiter = new Ratelimit({
      redis,
      limiter: Ratelimit.slidingWindow(5, "1 h"),
      analytics: true,
      prefix: "snapspec:email"
    });
  } catch (error) {
    console.error("Failed to initialize email rate limiting. Requests will not be limited.", error);
    emailLimiter = null;
  }

  return emailLimiter;
}

function getClientIp(request: NextRequest) {
  const forwardedFor = request.headers.get("x-forwarded-for");
  if (forwardedFor) return forwardedFor.split(",")[0]?.trim() || "unknown";
  return request.headers.get("x-real-ip") || "unknown";
}

function isValidEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function buildEmailHtml(
  jira: string,
  notion: string,
  confluence: string,
  screenshots: Array<EmailScreenshotPayload & { contentId: string }>
) {
  const escape = (str: string) =>
    str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const section = (title: string, content: string) => `
    <div style="margin-bottom:32px;">
      <h2 style="font-size:16px;font-weight:600;color:#18181b;margin:0 0 12px 0;padding-bottom:8px;border-bottom:1px solid #e4e4e7;">
        ${title}
      </h2>
      <pre style="font-family:ui-monospace,monospace;font-size:13px;line-height:1.7;color:#3f3f46;white-space:pre-wrap;word-break:break-word;margin:0;background:#fafafa;border:1px solid #e4e4e7;border-radius:12px;padding:16px;">${escape(content || "No content generated.")}</pre>
    </div>`;

  const screenshotsSection = screenshots.length
    ? `
    <div style="margin-bottom:32px;">
      <h2 style="font-size:16px;font-weight:600;color:#18181b;margin:0 0 12px 0;padding-bottom:8px;border-bottom:1px solid #e4e4e7;">
        Uploaded Screenshots
      </h2>
      <p style="font-size:13px;line-height:1.7;color:#71717a;margin:0 0 16px 0;">
        Included in the same order they were uploaded to SnapSpec.
      </p>
      ${screenshots
        .map(
          (screenshot, index) => `
            <div style="margin-bottom:20px;">
              <div style="font-size:13px;font-weight:600;color:#18181b;margin:0 0 10px 0;">
                Step ${index + 1}: ${escape(screenshot.filename)}
              </div>
              <div style="border:1px solid #e4e4e7;border-radius:16px;padding:12px;background:#fafafa;">
                <img src="cid:${escape(screenshot.contentId)}" alt="${escape(screenshot.filename)}" style="display:block;width:100%;height:auto;border-radius:12px;" />
              </div>
            </div>`
        )
        .join("")}
    </div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width,initial-scale=1" /></head>
<body style="margin:0;padding:0;background:#ffffff;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#ffffff;">
    <tr>
      <td align="center" style="padding:40px 16px;">
        <table width="100%" style="max-width:640px;">

          <tr>
            <td style="padding-bottom:32px;">
              <div style="display:inline-flex;align-items:center;gap:8px;border:1px solid #e4e4e7;border-radius:999px;padding:6px 14px;font-size:13px;color:#52525b;font-weight:500;">
                ✦ SnapSpec
              </div>
            </td>
          </tr>

          <tr>
            <td style="padding-bottom:32px;">
              <h1 style="font-size:24px;font-weight:600;color:#09090b;margin:0 0 8px 0;letter-spacing:-0.02em;">
                Your specs are ready
              </h1>
              <p style="font-size:14px;color:#71717a;margin:0;line-height:1.6;">
                Generated by SnapSpec — Jira, Notion, and Confluence output from your screenshots.
              </p>
            </td>
          </tr>

          <tr>
            <td>
              ${screenshotsSection}
              ${section("Jira", jira)}
              ${section("Notion", notion)}
              ${section("Confluence", confluence)}
            </td>
          </tr>

          <tr>
            <td style="padding-top:32px;border-top:1px solid #e4e4e7;">
              <p style="font-size:12px;color:#a1a1aa;margin:0;text-align:center;">
                Sent from <a href="https://snapspec.ai" style="color:#52525b;text-decoration:none;">snapspec.ai</a> — from screenshots to production-ready specs.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function buildEmailText(jira: string, notion: string, confluence: string, screenshots: EmailScreenshotPayload[]) {
  const divider = "\n" + "-".repeat(50) + "\n\n";
  return [
    "YOUR SPECS FROM SNAPSPEC",
    "snapspec.ai\n",
    screenshots.length
      ? `SCREENSHOTS (${screenshots.length})\n${screenshots.map((s, index) => `Step ${index + 1}: ${s.filename}`).join("\n")}\n${divider}`
      : "",
    "JIRA\n",
    jira || "No content generated.",
    divider,
    "NOTION\n",
    notion || "No content generated.",
    divider,
    "CONFLUENCE\n",
    confluence || "No content generated."
  ].join("\n");
}

export async function POST(req: NextRequest) {
  try {
    const ip = getClientIp(req);

    const body = await req.json() as {
      email?: unknown;
      jira?: unknown;
      notion?: unknown;
      confluence?: unknown;
      screenshots?: unknown;
    };

    const { email, jira = "", notion = "", confluence = "", screenshots = [] } = body;

    if (!email || typeof email !== "string" || !isValidEmail(email)) {
      return NextResponse.json({ error: "A valid email address is required." }, { status: 400 });
    }

    if (
      typeof jira !== "string" ||
      typeof notion !== "string" ||
      typeof confluence !== "string"
    ) {
      return NextResponse.json({ error: "Invalid spec content." }, { status: 400 });
    }

    if (!jira.trim() && !notion.trim() && !confluence.trim()) {
      return NextResponse.json({ error: "No spec content to send." }, { status: 400 });
    }

    if (!Array.isArray(screenshots)) {
      return NextResponse.json({ error: "Invalid screenshots payload." }, { status: 400 });
    }

    const normalizedScreenshots = screenshots.map((screenshot, index) => {
      if (
        !screenshot ||
        typeof screenshot !== "object" ||
        typeof screenshot.content !== "string" ||
        typeof screenshot.contentType !== "string" ||
        typeof screenshot.filename !== "string"
      ) {
        throw new Error(`Invalid screenshot payload at index ${index}.`);
      }

      const normalized = {
        content: screenshot.content.trim(),
        contentType: screenshot.contentType.trim(),
        filename: screenshot.filename.trim()
      };

      if (!normalized.content || !normalized.filename || !normalized.contentType.startsWith("image/")) {
        throw new Error(`Invalid screenshot payload at index ${index}.`);
      }

      return normalized;
    });

    const limiter = getEmailLimiter();

    if (limiter) {
      const rateLimitResult = await limiter.limit(`email:${ip}`);
      if (!rateLimitResult.success) {
        return NextResponse.json(
          { error: "Too many email requests. Please wait before sending again." },
          {
            status: 429,
            headers: {
              "Retry-After": String(Math.max(1, Math.ceil((rateLimitResult.reset - Date.now()) / 1000)))
            }
          }
        );
      }
    }

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json({ error: "Email service is not configured." }, { status: 500 });
    }

    const emailScreenshots = normalizedScreenshots.map((screenshot, index) => ({
      ...screenshot,
      contentId: `snapspec-step-${index + 1}`
    }));

    const { error } = await resend.emails.send({
      from: FROM_EMAIL,
      to: email,
      subject: "Your SnapSpec — Jira, Notion & Confluence specs",
      html: buildEmailHtml(String(jira), String(notion), String(confluence), emailScreenshots),
      text: buildEmailText(String(jira), String(notion), String(confluence), normalizedScreenshots),
      attachments: emailScreenshots.map((screenshot, index) => ({
        content: screenshot.content,
        contentId: screenshot.contentId,
        contentType: screenshot.contentType,
        filename: `step-${index + 1}-${screenshot.filename}`
      }))
    });

    if (error) {
      return NextResponse.json({ error: "Failed to send email. Please try again." }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unexpected error sending email.";
    if (message.startsWith("Invalid screenshot payload")) {
      return NextResponse.json({ error: "Invalid screenshots payload." }, { status: 400 });
    }
    return NextResponse.json({ error: "Unexpected error sending email." }, { status: 500 });
  }
}
